PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS hotels;
DROP TABLE IF EXISTS house_rules;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS hotel_bookings;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS blogs;